apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "frontend-svc"
  description: "Frontend service for my app"
  annotations:
    argocd/app-name: frontend-svc-dev
    backstage.io/kubernetes-id: frontend-svc
    backstage.io/kubernetes-namespace: frontend-svc-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: LiorJanus/frontend-svc
    quay.io/repository-slug: "liorjanus/frontend-svc"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-cl4w8.cl4w8.sandbox526.opentlc.com/#https://github.com/LiorJanus/frontend-svc?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-cl4w8.cl4w8.sandbox526.opentlc.com/#https://github.com/LiorJanus/frontend-svc?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/lior"
  providesApis:
    - "frontend-svc"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "frontend-svc"
  description: "Frontend service for my app"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/lior"
  definition:
    $text: ./openapi.yaml
